# Form implementation generated from reading ui file 'D:\do_an\ui\MainWindowEmployee.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 376)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 521, 381))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/tmanhuynh/Downloads/FARMERS\'(1).png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 130, 251, 221))
        self.groupBox_2.setStyleSheet("background-color: rgb(180, 255, 185);\n"
"font: 25 10pt \"Perpetua Titling MT\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 35, 10))
        self.label_2.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 25 9pt \"Perpetua Titling MT\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 35, 21))
        self.label_3.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 25 9pt \"Perpetua Titling MT\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(-10, 110, 71, 21))
        self.label_4.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 25 9pt \"Perpetua Titling MT\";")
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEditName = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditName.setGeometry(QtCore.QRect(60, 60, 141, 31))
        self.lineEditName.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #ff66b2;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditUserName.setGeometry(QtCore.QRect(60, 100, 141, 31))
        self.lineEditUserName.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #ff66b2;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonSave.setGeometry(QtCore.QRect(20, 180, 91, 31))
        self.pushButtonSave.setStyleSheet("\n"
"QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: 14pt \"Times New Roman\";\n"
"\n"
"}\n"
"QPushButton:enabled {\n"
"        background-color: white;\n"
"        color: Black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #0d2f72;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #E1F4FF;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\do_an\\ui\\../../Chuong4/BaiTap85/images/2931171_download_import_save_down_storage_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSave.setIcon(icon)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonRemove = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonRemove.setGeometry(QtCore.QRect(140, 180, 81, 31))
        self.pushButtonRemove.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: 14pt \"Times New Roman\";\n"
"\n"
"}\n"
"QPushButton:enabled {\n"
"        background-color: white;\n"
"        color: Black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #0d2f72;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #E1F4FF;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\do_an\\ui\\../../Chuong4/BaiTap85/images/185090_delete_garbage_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonRemove.setIcon(icon1)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.lineEditId = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditId.setGeometry(QtCore.QRect(60, 20, 141, 31))
        self.lineEditId.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #ff66b2;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Segoe UI\";\n"
"}")
        self.lineEditId.setObjectName("lineEditId")
        self.lineEditUserPassword = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditUserPassword.setGeometry(QtCore.QRect(60, 140, 141, 31))
        self.lineEditUserPassword.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #ff66b2;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.lineEditUserPassword.setObjectName("lineEditUserPassword")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(-10, 140, 71, 21))
        self.label_6.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 25 9pt \"Perpetua Titling MT\";")
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.tableWidgetProduct = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetProduct.setGeometry(QtCore.QRect(0, 129, 271, 200))
        self.tableWidgetProduct.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tableWidgetProduct.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.tableWidgetProduct.setObjectName("tableWidgetProduct")
        self.tableWidgetProduct.setColumnCount(3)
        self.tableWidgetProduct.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(4, 2, item)
        self.pushButtonexport_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonexport_2.setGeometry(QtCore.QRect(100, 340, 61, 21))
        self.pushButtonexport_2.setObjectName("pushButtonexport_2")
        self.pushButtonImport_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonImport_2.setGeometry(QtCore.QRect(20, 340, 61, 21))
        self.pushButtonImport_2.setObjectName("pushButtonImport_2")
        self.pushButtonexit_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonexit_2.setGeometry(QtCore.QRect(190, 350, 61, 20))
        self.pushButtonexit_2.setObjectName("pushButtonexit_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Employee Details"))
        self.label_2.setText(_translate("MainWindow", "id"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Username"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonRemove.setText(_translate("MainWindow", "Remove"))
        self.label_6.setText(_translate("MainWindow", "Password"))
        item = self.tableWidgetProduct.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetProduct.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetProduct.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidgetProduct.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidgetProduct.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidgetProduct.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetProduct.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidgetProduct.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "UserName"))
        __sortingEnabled = self.tableWidgetProduct.isSortingEnabled()
        self.tableWidgetProduct.setSortingEnabled(False)
        item = self.tableWidgetProduct.item(0, 0)
        item.setText(_translate("MainWindow", "Product 1"))
        item = self.tableWidgetProduct.item(0, 1)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidgetProduct.item(0, 2)
        item.setText(_translate("MainWindow", "c1"))
        item = self.tableWidgetProduct.item(1, 0)
        item.setText(_translate("MainWindow", "Product 2"))
        item = self.tableWidgetProduct.item(1, 1)
        item.setText(_translate("MainWindow", "23"))
        item = self.tableWidgetProduct.item(1, 2)
        item.setText(_translate("MainWindow", "c2"))
        item = self.tableWidgetProduct.item(2, 0)
        item.setText(_translate("MainWindow", "Product 3"))
        item = self.tableWidgetProduct.item(2, 1)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidgetProduct.item(2, 2)
        item.setText(_translate("MainWindow", "c3"))
        item = self.tableWidgetProduct.item(3, 0)
        item.setText(_translate("MainWindow", "Product 4"))
        item = self.tableWidgetProduct.item(3, 1)
        item.setText(_translate("MainWindow", "56"))
        item = self.tableWidgetProduct.item(3, 2)
        item.setText(_translate("MainWindow", "c4"))
        item = self.tableWidgetProduct.item(4, 0)
        item.setText(_translate("MainWindow", "Product 5"))
        item = self.tableWidgetProduct.item(4, 1)
        item.setText(_translate("MainWindow", "32"))
        item = self.tableWidgetProduct.item(4, 2)
        item.setText(_translate("MainWindow", "c5"))
        self.tableWidgetProduct.setSortingEnabled(__sortingEnabled)
        self.pushButtonexport_2.setText(_translate("MainWindow", "Export"))
        self.pushButtonImport_2.setText(_translate("MainWindow", "Import"))
        self.pushButtonexit_2.setText(_translate("MainWindow", "Exit"))
