# Form implementation generated from reading ui file 'D:\PyCharm\ProjectISM\uis\ui_employee\MainWindowEmployee.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 577)
        MainWindow.setStyleSheet("QMenuBar {\n"
"    background-color: #00806c;  /* Màu nền */\n"
"    color: White;  /* Màu chữ */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QMenuBar::item:selected { \n"
"    background-color: #86ad6f;  /* Màu khi hover */\n"
"}\n"
"QTableWidget {\n"
"    background-color: #d2e3c3; /* Màu nền */\n"
"        gridline-color: #006400; /* Màu đường kẻ */\n"
"    font-size: 12pt;\n"
"    font-family: \"Times New Roman\";\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #00806c; /* Màu nền tiêu đề bảng */\n"
"    color: White;\n"
"    font-weight: bold;\n"
"    border: 1px solid #006400;\n"
"}\n"
"QTableCornerButton::section {\n"
"    background-color: #00806c; /* Cùng màu với tiêu đề */\n"
"    border: 1px solid #006400;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 821, 531))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\PyCharm\\ProjectISM\\uis\\ui_employee\\../images/FARMERS\'(3).png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 220, 811, 341))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #00806c; /* Viền xanh đậm */\n"
"    border-radius: 5px; /* Bo góc nhẹ */\n"
"    margin-top: 10px; /* Đẩy tiêu đề lên trên viền */\n"
"    font: bold 14pt \"Tahoma\"; /* Chữ in đậm */\n"
"    color: #00806c; /* Màu chữ xanh ngọc */\n"
"    background-color: rgb(208, 225, 193);\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* Tiêu đề nằm góc trái */\n"
"    padding: 2px 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"QLabel {\n"
"    font: bold 10pt \"Tahoma\";        /* Cỡ chữ */\n"
"    color: #00806c;             /* Màu chữ */\n"
"    font-weight: bold;      /* Chữ đậm */\n"
"}\n"
"QLineEdit {\n"
"    font-size: 16px;        /* Cỡ chữ */\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonSave.setGeometry(QtCore.QRect(580, 280, 91, 41))
        self.pushButtonSave.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\PyCharm\\ProjectISM\\uis\\ui_employee\\../images/134229_cloud_guardar_save_store_up_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSave.setIcon(icon)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonRemove = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonRemove.setGeometry(QtCore.QRect(460, 280, 91, 41))
        self.pushButtonRemove.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\PyCharm\\ProjectISM\\uis\\ui_employee\\../images/8664938_trash_can_delete_remove_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonRemove.setIcon(icon1)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.pushButtonClear = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonClear.setGeometry(QtCore.QRect(130, 280, 91, 41))
        self.pushButtonClear.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\PyCharm\\ProjectISM\\uis\\ui_employee\\../images/3669378_clear_ic_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonClear.setIcon(icon2)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonSearch.setGeometry(QtCore.QRect(240, 280, 91, 41))
        self.pushButtonSearch.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\PyCharm\\ProjectISM\\uis\\ui_employee\\../images/211817_search_strong_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSearch.setIcon(icon3)
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.lineEditAddress = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditAddress.setGeometry(QtCore.QRect(570, 230, 221, 41))
        self.lineEditAddress.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #00806c;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Tahoma\";\n"
"}")
        self.lineEditAddress.setObjectName("lineEditAddress")
        self.lineEditShift = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditShift.setGeometry(QtCore.QRect(570, 130, 221, 41))
        self.lineEditShift.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #00806c;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Tahoma\";\n"
"}")
        self.lineEditShift.setObjectName("lineEditShift")
        self.lineEditLevel = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditLevel.setGeometry(QtCore.QRect(570, 80, 221, 41))
        self.lineEditLevel.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #00806c;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Tahoma\";\n"
"}")
        self.lineEditLevel.setObjectName("lineEditLevel")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditEmail.setGeometry(QtCore.QRect(570, 30, 221, 41))
        self.lineEditEmail.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #00806c;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Tahoma\";\n"
"}")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEditNumber = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditNumber.setGeometry(QtCore.QRect(570, 180, 221, 41))
        self.lineEditNumber.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #00806c;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Tahoma\";\n"
"}")
        self.lineEditNumber.setObjectName("lineEditNumber")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(460, 130, 81, 41))
        self.label_9.setStyleSheet("font: 11pt \"Tahoma\";")
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(460, 180, 91, 41))
        self.label_10.setStyleSheet("font: 11pt \"Tahoma\";")
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(460, 39, 91, 31))
        self.label_12.setStyleSheet("font: 11pt \"Tahoma\";")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(460, 90, 71, 21))
        self.label_13.setStyleSheet("font: 12pt \"Tahoma\";")
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(460, 230, 91, 41))
        self.label_14.setStyleSheet("font: 11pt \"Tahoma\";")
        self.label_14.setScaledContents(False)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.pushButtonUpdate = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonUpdate.setGeometry(QtCore.QRect(700, 280, 91, 41))
        self.pushButtonUpdate.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\PyCharm\\ProjectISM\\uis\\ui_employee\\../images/1564533_arrow_refrech_reload_update_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonUpdate.setIcon(icon4)
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.pushButtonShowAll = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonShowAll.setGeometry(QtCore.QRect(20, 280, 91, 41))
        self.pushButtonShowAll.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("D:\\PyCharm\\ProjectISM\\uis\\ui_employee\\../images/all_5578931.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonShowAll.setIcon(icon5)
        self.pushButtonShowAll.setIconSize(QtCore.QSize(24, 12))
        self.pushButtonShowAll.setObjectName("pushButtonShowAll")
        self.label_18 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(40, 230, 91, 41))
        self.label_18.setStyleSheet("font: 11pt \"Tahoma\";")
        self.label_18.setScaledContents(False)
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.lineEditUserRole = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditUserRole.setGeometry(QtCore.QRect(160, 230, 221, 41))
        self.lineEditUserRole.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #00806c;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Tahoma\";\n"
"}")
        self.lineEditUserRole.setObjectName("lineEditUserRole")
        self.lineEditId = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditId.setGeometry(QtCore.QRect(160, 30, 221, 41))
        self.lineEditId.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #00806c;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Tahoma\";\n"
"}")
        self.lineEditId.setObjectName("lineEditId")
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(40, 70, 131, 51))
        self.label_15.setStyleSheet("font: 12pt \"Tahoma\";")
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(40, 130, 81, 41))
        self.label_11.setStyleSheet("font: 11pt \"Tahoma\";")
        self.label_11.setScaledContents(False)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditUserName.setGeometry(QtCore.QRect(160, 130, 221, 41))
        self.lineEditUserName.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #00806c;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Tahoma\";\n"
"}")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditUserPassword = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditUserPassword.setGeometry(QtCore.QRect(160, 180, 221, 41))
        self.lineEditUserPassword.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #00806c;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Tahoma\";\n"
"}")
        self.lineEditUserPassword.setObjectName("lineEditUserPassword")
        self.label_16 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(40, 30, 111, 31))
        self.label_16.setStyleSheet("font: 11pt \"Tahoma\";")
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.lineEditName = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditName.setGeometry(QtCore.QRect(160, 80, 221, 41))
        self.lineEditName.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #00806c;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Tahoma\";\n"
"}")
        self.lineEditName.setObjectName("lineEditName")
        self.label_17 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(40, 180, 91, 41))
        self.label_17.setStyleSheet("font: 11pt \"Tahoma\";")
        self.label_17.setScaledContents(False)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.tableWidgetProduct = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetProduct.setGeometry(QtCore.QRect(10, 70, 811, 151))
        self.tableWidgetProduct.setMaximumSize(QtCore.QSize(16777215, 500))
        self.tableWidgetProduct.setStyleSheet("font: 11pt \"Tahoma\";\n"
"background-color: rgb(208, 225, 193);")
        self.tableWidgetProduct.setObjectName("tableWidgetProduct")
        self.tableWidgetProduct.setColumnCount(10)
        self.tableWidgetProduct.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(4, 3, item)
        self.tableWidgetProduct.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidgetProduct.verticalHeader().setDefaultSectionSize(30)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 20, 641, 31))
        self.label_5.setStyleSheet("font: 24pt \"Tahoma\";\n"
"color: rgb(26, 140, 118);")
        self.label_5.setObjectName("label_5")
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(20, 10, 81, 41))
        self.pushButtonBack.setObjectName("pushButtonBack")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 821, 31))
        self.menuBar.setObjectName("menuBar")
        self.menuOptions = QtWidgets.QMenu(parent=self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuExit = QtWidgets.QMenu(parent=self.menuBar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menuBar)
        self.actionImport = QtGui.QAction(parent=MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("D:\\PyCharm\\ProjectISM\\uis\\ui_employee\\../images/2931171_download_import_save_down_storage_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionImport.setIcon(icon6)
        self.actionImport.setObjectName("actionImport")
        self.actionExxport = QtGui.QAction(parent=MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("D:\\PyCharm\\ProjectISM\\uis\\ui_employee\\../images/2931143_export_share_upload_up_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExxport.setIcon(icon7)
        self.actionExxport.setObjectName("actionExxport")
        self.actionHelp = QtGui.QAction(parent=MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("D:\\PyCharm\\ProjectISM\\uis\\ui_employee\\../images/211757_help_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionHelp.setIcon(icon8)
        self.actionHelp.setObjectName("actionHelp")
        self.menuOptions.addAction(self.actionImport)
        self.menuOptions.addAction(self.actionExxport)
        self.menuOptions.addAction(self.actionHelp)
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Employee Details"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonRemove.setText(_translate("MainWindow", "Remove"))
        self.pushButtonClear.setText(_translate("MainWindow", "Clear"))
        self.pushButtonSearch.setText(_translate("MainWindow", "Search"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#00806c;\">Shift:</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#00806c;\">Number:</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#00806c;\">Email:</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#00806c;\">Level:</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#00806c;\">Address:</span></p></body></html>"))
        self.pushButtonUpdate.setText(_translate("MainWindow", "Update"))
        self.pushButtonShowAll.setText(_translate("MainWindow", "Show All"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#00806c;\">Role:</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#00806c;\"> Name:</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#00806c;\">Username:</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#00806c;\">Employee ID:</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#00806c;\">Password:</span></p></body></html>"))
        item = self.tableWidgetProduct.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetProduct.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetProduct.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidgetProduct.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidgetProduct.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidgetProduct.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidgetProduct.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidgetProduct.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidgetProduct.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidgetProduct.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Employee ID"))
        item = self.tableWidgetProduct.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Employee Name"))
        item = self.tableWidgetProduct.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidgetProduct.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidgetProduct.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Role"))
        item = self.tableWidgetProduct.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidgetProduct.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Level"))
        item = self.tableWidgetProduct.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Shift"))
        item = self.tableWidgetProduct.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Number"))
        item = self.tableWidgetProduct.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Address"))
        __sortingEnabled = self.tableWidgetProduct.isSortingEnabled()
        self.tableWidgetProduct.setSortingEnabled(False)
        item = self.tableWidgetProduct.item(0, 0)
        item.setText(_translate("MainWindow", "P1"))
        item = self.tableWidgetProduct.item(0, 1)
        item.setText(_translate("MainWindow", "Product 1"))
        item = self.tableWidgetProduct.item(0, 2)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidgetProduct.item(0, 3)
        item.setText(_translate("MainWindow", "23"))
        item = self.tableWidgetProduct.item(1, 0)
        item.setText(_translate("MainWindow", "P2"))
        item = self.tableWidgetProduct.item(1, 1)
        item.setText(_translate("MainWindow", "Product 2"))
        item = self.tableWidgetProduct.item(1, 2)
        item.setText(_translate("MainWindow", "23"))
        item = self.tableWidgetProduct.item(1, 3)
        item.setText(_translate("MainWindow", "21"))
        item = self.tableWidgetProduct.item(2, 0)
        item.setText(_translate("MainWindow", "P3"))
        item = self.tableWidgetProduct.item(2, 1)
        item.setText(_translate("MainWindow", "Product 3"))
        item = self.tableWidgetProduct.item(2, 2)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidgetProduct.item(2, 3)
        item.setText(_translate("MainWindow", "43"))
        item = self.tableWidgetProduct.item(3, 0)
        item.setText(_translate("MainWindow", "P4"))
        item = self.tableWidgetProduct.item(3, 1)
        item.setText(_translate("MainWindow", "Product 4"))
        item = self.tableWidgetProduct.item(3, 2)
        item.setText(_translate("MainWindow", "56"))
        item = self.tableWidgetProduct.item(3, 3)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetProduct.item(4, 0)
        item.setText(_translate("MainWindow", "P5"))
        item = self.tableWidgetProduct.item(4, 1)
        item.setText(_translate("MainWindow", "Product 5"))
        item = self.tableWidgetProduct.item(4, 2)
        item.setText(_translate("MainWindow", "32"))
        item = self.tableWidgetProduct.item(4, 3)
        item.setText(_translate("MainWindow", "56"))
        self.tableWidgetProduct.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#00806c;\">EMPLOYEE MANAGEMENT</span></p></body></html>"))
        self.pushButtonBack.setText(_translate("MainWindow", "Back "))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuExit.setTitle(_translate("MainWindow", "l"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionExxport.setText(_translate("MainWindow", "Export"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
