# Form implementation generated from reading ui file 'D:\PyCharm\test_github2\Midterm_NgoThiPhuongThao\ui\LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1178, 829)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 1181, 831))
        self.label_4.setMaximumSize(QtCore.QSize(500000, 500000))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\\PyCharm\\test_github2\\Midterm_NgoThiPhuongThao\\ui\\../../../../Downloads/2.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 660, 421, 81))
        self.label_7.setStyleSheet("font: 20pt \"Tahoma\";\n"
"color: rgb(0, 128, 108);")
        self.label_7.setObjectName("label_7")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(660, 570, 231, 51))
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: 16pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #0d2f72;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}\n"
"")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(380, 570, 231, 51))
        self.pushButtonLogin.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: 16pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #0d2f72;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}\n"
"")
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserName.setGeometry(QtCore.QRect(420, 300, 491, 51))
        self.lineEditUserName.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 4px solid #00806c;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 400, 141, 51))
        self.label_3.setStyleSheet("font: 75 18pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(420, 400, 491, 51))
        self.lineEditPassword.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 4px solid #00806c;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Segoe UI\";\n"
"}")
        self.lineEditPassword.setText("")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 300, 161, 51))
        self.label_2.setStyleSheet("font: 75 18pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.AdminRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.AdminRadio.setGeometry(QtCore.QRect(580, 480, 111, 41))
        self.AdminRadio.setStyleSheet("font:  14pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);")
        self.AdminRadio.setObjectName("AdminRadio")
        self.StaffRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.StaffRadio.setGeometry(QtCore.QRect(750, 480, 111, 41))
        self.StaffRadio.setStyleSheet("font:  14pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);")
        self.StaffRadio.setObjectName("StaffRadio")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(420, 470, 141, 51))
        self.label_5.setStyleSheet("font: 75 18pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "K244060778"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600;\">LOGIN</span></p></body></html>"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Login"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Password:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">UserName:</span></p></body></html>"))
        self.AdminRadio.setText(_translate("MainWindow", "Admin"))
        self.StaffRadio.setText(_translate("MainWindow", "Staff"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Login as:</span></p></body></html>"))
