# Form implementation generated from reading ui file 'D:\PyCharm\pythonProject2\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1021, 766)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonBarChart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBarChart.setGeometry(QtCore.QRect(40, 670, 241, 41))
        self.pushButtonBarChart.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\PyCharm\\pythonProject2\\ui\\../images/bar-chart(1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBarChart.setIcon(icon)
        self.pushButtonBarChart.setObjectName("pushButtonBarChart")
        self.pushButtonLineChart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLineChart.setGeometry(QtCore.QRect(370, 670, 261, 41))
        self.pushButtonLineChart.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\PyCharm\\pythonProject2\\ui\\../images/line-chart(1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLineChart.setIcon(icon1)
        self.pushButtonLineChart.setObjectName("pushButtonLineChart")
        self.pushButtonPieChart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPieChart.setGeometry(QtCore.QRect(760, 670, 221, 41))
        self.pushButtonPieChart.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\PyCharm\\pythonProject2\\ui\\../images/pie-chart(1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPieChart.setIcon(icon2)
        self.pushButtonPieChart.setObjectName("pushButtonPieChart")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(30, 10, 91, 41))
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\PyCharm\\pythonProject2\\ui\\../images/exit-full-screen(1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon3)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 70, 951, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 15, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonBarChart.setText(_translate("MainWindow", "Bar Chart"))
        self.pushButtonLineChart.setText(_translate("MainWindow", "Line Chart"))
        self.pushButtonPieChart.setText(_translate("MainWindow", "Pie Chart"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; color:#00aa00;\">Visualization</span></p></body></html>"))
