# Form implementation generated from reading ui file 'D:\do_an\ui\MainWindowEmployee2.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(584, 390)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 591, 391))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/tmanhuynh/Downloads/FARMERS\'(1).png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 110, 291, 221))
        self.groupBox_2.setStyleSheet("background-color: rgb(180, 255, 185);\n"
"font: 25 10pt \"Perpetua Titling MT\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 41, 20))
        self.label_2.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 25 9pt \"Perpetua Titling MT\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 51, 21))
        self.label_3.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 25 9pt \"Perpetua Titling MT\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(0, 100, 81, 21))
        self.label_4.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 25 9pt \"Perpetua Titling MT\";")
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEditName = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditName.setGeometry(QtCore.QRect(80, 60, 191, 31))
        self.lineEditName.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #ff66b2;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditUserName.setGeometry(QtCore.QRect(80, 100, 191, 31))
        self.lineEditUserName.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #ff66b2;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonSave.setGeometry(QtCore.QRect(50, 180, 91, 31))
        self.pushButtonSave.setStyleSheet("\n"
"QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: 14pt \"Times New Roman\";\n"
"\n"
"}\n"
"QPushButton:enabled {\n"
"        background-color: white;\n"
"        color: Black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #0d2f72;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #E1F4FF;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\do_an\\ui\\../../Chuong4/BaiTap85/images/2931171_download_import_save_down_storage_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSave.setIcon(icon)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonRemove = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonRemove.setGeometry(QtCore.QRect(180, 180, 91, 31))
        self.pushButtonRemove.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: 14pt \"Times New Roman\";\n"
"\n"
"}\n"
"QPushButton:enabled {\n"
"        background-color: white;\n"
"        color: Black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #0d2f72;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #E1F4FF;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\do_an\\ui\\../../Chuong4/BaiTap85/images/185090_delete_garbage_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonRemove.setIcon(icon1)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.lineEditId = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditId.setGeometry(QtCore.QRect(80, 20, 191, 31))
        self.lineEditId.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #ff66b2;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Segoe UI\";\n"
"}")
        self.lineEditId.setObjectName("lineEditId")
        self.lineEditUserPassword = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditUserPassword.setGeometry(QtCore.QRect(80, 140, 191, 31))
        self.lineEditUserPassword.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #ff66b2;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.lineEditUserPassword.setObjectName("lineEditUserPassword")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(0, 140, 81, 21))
        self.label_6.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 25 9pt \"Perpetua Titling MT\";")
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pushButtonexport_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonexport_2.setGeometry(QtCore.QRect(100, 330, 71, 31))
        self.pushButtonexport_2.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: 14pt \"Times New Roman\";\n"
"\n"
"}\n"
"QPushButton:enabled {\n"
"        background-color: white;\n"
"        color: Black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #0d2f72;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #E1F4FF;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}")
        self.pushButtonexport_2.setObjectName("pushButtonexport_2")
        self.pushButtonImport_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonImport_2.setGeometry(QtCore.QRect(20, 330, 71, 31))
        self.pushButtonImport_2.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: 14pt \"Times New Roman\";\n"
"\n"
"}\n"
"QPushButton:enabled {\n"
"        background-color: white;\n"
"        color: Black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #0d2f72;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #E1F4FF;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}")
        self.pushButtonImport_2.setObjectName("pushButtonImport_2")
        self.pushButtonexit_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonexit_2.setGeometry(QtCore.QRect(190, 330, 71, 31))
        self.pushButtonexit_2.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: 14pt \"Times New Roman\";\n"
"\n"
"}\n"
"QPushButton:enabled {\n"
"        background-color: white;\n"
"        color: Black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #0d2f72;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #E1F4FF;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}")
        self.pushButtonexit_2.setObjectName("pushButtonexit_2")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 110, 271, 211))
        self.groupBox.setStyleSheet("font: 25 10pt \"Perpetua Titling MT\";")
        self.groupBox.setObjectName("groupBox")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.groupBox)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 249, 189))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 231, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Employee Details"))
        self.label_2.setText(_translate("MainWindow", "id"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Username"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonRemove.setText(_translate("MainWindow", "Remove"))
        self.label_6.setText(_translate("MainWindow", "Password"))
        self.pushButtonexport_2.setText(_translate("MainWindow", "Export"))
        self.pushButtonImport_2.setText(_translate("MainWindow", "Import"))
        self.pushButtonexit_2.setText(_translate("MainWindow", "Exit"))
        self.groupBox.setTitle(_translate("MainWindow", "Assets"))
