# Form implementation generated from reading ui file 'C:\Users\phuongthao\PycharmProjects\k244060803_NgoThiPhuongThao_406H\Midterm_NgoThiPhuongThao\ui\LoginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1302, 822)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(11, 11, 1280, 800))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\k244060803_NgoThiPhuongThao_406H\\Midterm_NgoThiPhuongThao\\ui\\../../../../Downloads/✅ (1).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserName.setGeometry(QtCore.QRect(130, 290, 351, 41))
        self.lineEditUserName.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #ff66b2;  /* Viền màu xanh */\n"
"    border-radius: 15px;        /* Bo tròn góc */\n"
"    padding: 5px;               /* Khoảng cách chữ với viền */\n"
"    background-color: white;    /* Màu nền */\n"
"}\n"
"")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(130, 440, 351, 41))
        self.lineEditPassword.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #ff66b2;  /* Viền màu xanh */\n"
"    border-radius: 15px;        /* Bo tròn góc */\n"
"    padding: 5px;               /* Khoảng cách chữ với viền */\n"
"    background-color: white;    /* Màu nền */\n"
"}\n"
"")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.checkBoxSinhVien = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxSinhVien.setGeometry(QtCore.QRect(260, 500, 221, 41))
        self.checkBoxSinhVien.setStyleSheet("QCheckBox {\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    spacing: 10px; /* Khoảng cách giữa checkbox và chữ */\n"
"    font-size: 14px; /* Kích thước chữ */\n"
"    color: #2c3e50; /* Màu chữ */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px; /* Bo tròn góc */\n"
"    border: 2px solid #ff66b2; /* Viền màu hồng */\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #ff66b2; /* Màu nền khi được chọn */\n"
"    border: 2px solid #e91e63; /* Viền khi được chọn */\n"
"}\n"
"")
        self.checkBoxSinhVien.setObjectName("checkBoxSinhVien")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(150, 640, 111, 41))
        self.pushButtonLogin.setStyleSheet("QPushButton {\n"
"    background-color: #ff66b2;  /* Nền hồng */\n"
"    border: 2px solid white;    /* Viền trắng */\n"
"    border-radius: 10px;        /* Bo tròn góc */\n"
"    padding: 8px 16px;          /* Khoảng cách chữ với viền */\n"
"    font-size: 16px;            /* Kích thước chữ */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    font-weight: bold;          /* Chữ in đậm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e91e63;  /* Màu khi di chuột vào */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #c2185b;  /* Màu khi bấm */\n"
"    border: 2px solid #f1f1f1;  /* Viền trắng nhạt khi bấm */\n"
"}\n"
"")
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(350, 640, 111, 41))
        self.pushButtonExit.setStyleSheet("QPushButton {\n"
"    background-color: #ff66b2;  /* Nền hồng */\n"
"    border: 2px solid white;    /* Viền trắng */\n"
"    border-radius: 10px;        /* Bo tròn góc */\n"
"    padding: 8px 16px;          /* Khoảng cách chữ với viền */\n"
"    font-size: 16px;            /* Kích thước chữ */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    font-weight: bold;          /* Chữ in đậm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e91e63;  /* Màu khi di chuột vào */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #c2185b;  /* Màu khi bấm */\n"
"    border: 2px solid #f1f1f1;  /* Viền trắng nhạt khi bấm */\n"
"}\n"
"")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.checkBoxGiangVien = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxGiangVien.setGeometry(QtCore.QRect(260, 540, 221, 41))
        self.checkBoxGiangVien.setStyleSheet("QCheckBox {\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    spacing: 10px; /* Khoảng cách giữa checkbox và chữ */\n"
"    font-size: 14px; /* Kích thước chữ */\n"
"    color: #2c3e50; /* Màu chữ */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px; /* Bo tròn góc */\n"
"    border: 2px solid #ff66b2; /* Viền màu hồng */\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #ff66b2; /* Màu nền khi được chọn */\n"
"    border: 2px solid #e91e63; /* Viền khi được chọn */\n"
"}\n"
"")
        self.checkBoxGiangVien.setObjectName("checkBoxGiangVien")
        self.checkBoxThuThu = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxThuThu.setGeometry(QtCore.QRect(260, 580, 221, 41))
        self.checkBoxThuThu.setStyleSheet("QCheckBox {\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    spacing: 10px; /* Khoảng cách giữa checkbox và chữ */\n"
"    font-size: 14px; /* Kích thước chữ */\n"
"    color: #2c3e50; /* Màu chữ */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px; /* Bo tròn góc */\n"
"    border: 2px solid #ff66b2; /* Viền màu hồng */\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #ff66b2; /* Màu nền khi được chọn */\n"
"    border: 2px solid #e91e63; /* Viền khi được chọn */\n"
"}\n"
"")
        self.checkBoxThuThu.setObjectName("checkBoxThuThu")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ngô Thị Phương Thảo-K244060803"))
        self.checkBoxSinhVien.setText(_translate("MainWindow", "Sinh viên"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Login"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit "))
        self.checkBoxGiangVien.setText(_translate("MainWindow", "Giảng viên"))
        self.checkBoxThuThu.setText(_translate("MainWindow", "Thủ thư"))
