# Form implementation generated from reading ui file 'C:\Users\phuongthao\PycharmProjects\k244060803_NgoThiPhuongThao_406H\Midterm_NgoThiPhuongThao\ui\Manhinhtrunggian.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 536)
        MainWindow.setStyleSheet("QMenuBar {\n"
"    background-color: #d2e3c3;  /* Màu nền */\n"
"    color: #00806c;  /* Màu chữ */\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QMenuBar::item:selected { \n"
"    background-color: #86ad6f;  /* Màu khi hover */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 811, 511))
        self.label.setMouseTracking(True)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\k244060803_NgoThiPhuongThao_406H\\Midterm_NgoThiPhuongThao\\ui\\../../../../Downloads/nentrunggian.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 240, 81, 31))
        self.label_2.setMaximumSize(QtCore.QSize(16777205, 16777215))
        self.label_2.setStyleSheet("font:  14pt \"Segoe UI\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 290, 81, 31))
        self.label_3.setMaximumSize(QtCore.QSize(16777205, 16777215))
        self.label_3.setStyleSheet("font:  14pt \"Segoe UI\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 350, 81, 31))
        self.label_4.setMaximumSize(QtCore.QSize(16777205, 16777215))
        self.label_4.setStyleSheet("font:  14pt \"Segoe UI\";")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.labelName = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(320, 240, 321, 31))
        self.labelName.setMaximumSize(QtCore.QSize(16777205, 16777215))
        self.labelName.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.labelName.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.labelName.setAcceptDrops(False)
        self.labelName.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.labelName.setAutoFillBackground(False)
        self.labelName.setStyleSheet("font:  14pt \"Segoe UI\";")
        self.labelName.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelName.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.labelName.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.labelName.setScaledContents(False)
        self.labelName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelName.setWordWrap(False)
        self.labelName.setObjectName("labelName")
        self.labelID = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelID.setGeometry(QtCore.QRect(320, 290, 321, 31))
        self.labelID.setMaximumSize(QtCore.QSize(16777205, 16777215))
        self.labelID.setStyleSheet("font:  14pt \"Segoe UI\";")
        self.labelID.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelID.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelID.setObjectName("labelID")
        self.labelRole = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelRole.setGeometry(QtCore.QRect(320, 350, 321, 31))
        self.labelRole.setMaximumSize(QtCore.QSize(16777205, 16777215))
        self.labelRole.setMouseTracking(False)
        self.labelRole.setStyleSheet("font:  14pt \"Segoe UI\";")
        self.labelRole.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelRole.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.labelRole.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelRole.setObjectName("labelRole")
        self.pushButtonYes = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonYes.setGeometry(QtCore.QRect(210, 420, 171, 41))
        self.pushButtonYes.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font:14pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}\n"
"")
        self.pushButtonYes.setObjectName("pushButtonYes")
        self.pushButtonNo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonNo.setGeometry(QtCore.QRect(430, 420, 171, 41))
        self.pushButtonNo.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font:14pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}\n"
"")
        self.pushButtonNo.setObjectName("pushButtonNo")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 150, 421, 41))
        self.label_5.setMaximumSize(QtCore.QSize(16777205, 16777215))
        self.label_5.setStyleSheet("font:  14pt \"Segoe UI\";\n"
"color: rgb(0, 128, 108);")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 811, 31))
        self.menuBar.setObjectName("menuBar")
        self.menuOptions = QtWidgets.QMenu(parent=self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menuBar)
        self.actionInstruction = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\k244060803_NgoThiPhuongThao_406H\\Midterm_NgoThiPhuongThao\\ui\\../IMAGES/8207898_about_info_information_help_ui_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionInstruction.setIcon(icon)
        self.actionInstruction.setObjectName("actionInstruction")
        self.actionHelp = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\k244060803_NgoThiPhuongThao_406H\\Midterm_NgoThiPhuongThao\\ui\\../IMAGES/9044348_help_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionHelp.setIcon(icon1)
        self.actionHelp.setObjectName("actionHelp")
        self.actionFeedback = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\k244060803_NgoThiPhuongThao_406H\\Midterm_NgoThiPhuongThao\\ui\\../IMAGES/5740111_bubble_chat_comment_communication_feedback_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionFeedback.setIcon(icon2)
        self.actionFeedback.setObjectName("actionFeedback")
        self.menuOptions.addAction(self.actionInstruction)
        self.menuOptions.addAction(self.actionHelp)
        self.menuOptions.addAction(self.actionFeedback)
        self.menuBar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Confirm Window"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Name:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">ID:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Role:</span></p></body></html>"))
        self.labelName.setText(_translate("MainWindow", "Tên"))
        self.labelID.setText(_translate("MainWindow", "Mã "))
        self.labelRole.setText(_translate("MainWindow", "Vai trò"))
        self.pushButtonYes.setText(_translate("MainWindow", "YES"))
        self.pushButtonNo.setText(_translate("MainWindow", "NO"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">CONFIRM INFORMATION</span></p></body></html>"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionInstruction.setText(_translate("MainWindow", "Instruction"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionFeedback.setText(_translate("MainWindow", "Feedback"))
