# Form implementation generated from reading ui file 'C:\Users\phuongthao\PycharmProjects\chuong5\DOAN1\ui\ProductMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 771)
        MainWindow.setMaximumSize(QtCore.QSize(16777207, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../ima/famer.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMenuBar {\n"
"    background-color: #00806c;  /* Màu nền */\n"
"    color: White;  /* Màu chữ */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QMenuBar::item:selected { \n"
"    background-color: #86ad6f;  /* Màu khi hover */\n"
"}\n"
"QTableWidget {\n"
"    border: 2px solid #2E8B57; /* Viền màu xanh lá đậm */\n"
"    gridline-color: black;     /* Màu đường kẻ ô */\n"
"    background-color: #d2e3c3; /* Màu nền */\n"
"     gridline-color: #006400; /* Màu đường kẻ */\n"
"    font-size: 12pt;\n"
"    font-family: \"Times New Roman\";\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #00806c; /* Màu nền tiêu đề bảng */\n"
"    color: White;\n"
"    font-weight: bold;\n"
"    border: 1px solid #006400;\n"
"}\n"
"QTableCornerButton::section {\n"
"    background-color: #00806c; /* Cùng màu với tiêu đề */\n"
"    border: 1px solid #006400;\n"
"}\n"
"background-image: url(\"nentron.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-size: cover;\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 57, 1061, 671))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidgetCategory = QtWidgets.QListWidget(parent=self.layoutWidget)
        self.listWidgetCategory.setEnabled(True)
        self.listWidgetCategory.setMaximumSize(QtCore.QSize(500, 700))
        self.listWidgetCategory.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.listWidgetCategory.setStyleSheet("QListWidget::item:selected {\n"
"    background: #00806c;  /* Giữ màu nền xanh đậm */\n"
"    color: white;         /* Chữ trắng */\n"
"    font-weight: bold;\n"
"    border: none;         /* Bỏ viền trắng */\n"
"    outline: none;        /* Loại bỏ đường viền focus */\n"
"}\n"
"\n"
"QListWidget {\n"
"    border: 2px solid #00806c;  /* Viền xanh đậm */\n"
"    border-radius: 5px;         /* Bo góc nhẹ */\n"
"    background: transparent; /* Nền tổng thể xanh nhạt */\n"
"    font: bold 14pt \"Tahoma\";   /* Font chữ đậm */\n"
"    color: #00806c;             /* Chữ xanh đậm */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 10px;\n"
"    border-radius: 10px;           /* Bo tròn góc */\n"
"    background-color: rgb(186, 216, 171);  /* Xanh nhạt khác nền tổng thể */\n"
"    color: #00806c;                /* Chữ xanh đậm */\n"
"    margin: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: white;   /* Khi di chuột vào, nền trắng */\n"
"    color: #00806c;      /* Chữ vẫn xanh đậm */\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background: #00806c;  /* Màu xanh đậm khi chọn */\n"
"    color: white;         /* Chữ trắng để nổi bật */\n"
"    font-weight: bold;\n"
"    border: none; /* Bỏ viền khi chọn */\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    background: #00806c; /* Giữ màu khi focus */\n"
"    color: white; \n"
"    border: none;\n"
"    outline: none; /* Bỏ đường viền khi focus */\n"
"}")
        self.listWidgetCategory.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.listWidgetCategory.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.listWidgetCategory.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.listWidgetCategory.setFlow(QtWidgets.QListView.Flow.TopToBottom)
        self.listWidgetCategory.setObjectName("listWidgetCategory")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidgetCategory.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidgetCategory.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        item.setFont(font)
        self.listWidgetCategory.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidgetCategory.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidgetCategory.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidgetCategory.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidgetCategory.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidgetCategory.addItem(item)
        self.horizontalLayout_4.addWidget(self.listWidgetCategory)
        self.groupBox = QtWidgets.QGroupBox(parent=self.layoutWidget)
        self.groupBox.setMaximumSize(QtCore.QSize(500, 700))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #00806c; /* Viền xanh đậm */\n"
"    border-radius: 5px; /* Bo góc nhẹ */\n"
"    margin-top: 10px; /* Đẩy tiêu đề lên trên viền */\n"
"    font: bold 14pt \"Tahoma\"; /* Chữ in đậm */\n"
"    color: #00806c; /* Màu chữ xanh ngọc */\n"
"\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* Tiêu đề nằm góc trái */\n"
"    padding: 2px 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"QLabel {\n"
"    font: bold 12pt \"Tahoma\";        /* Cỡ chữ */\n"
"    color: #00806c;             /* Màu chữ */\n"
"    font-weight: bold;      /* Chữ đậm */\n"
"\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid #00806c; /* Viền xanh lá đậm */\n"
"    border-radius: 10px;       /* Bo tròn góc */\n"
"    padding: 5px;              /* Khoảng cách nội dung với viền */\n"
"    background-color: white;   /* Nền trắng */\n"
"     font-size: 15px;        /* Cỡ chữ */\n"
"}")
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.lineEditCateID = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditCateID.setGeometry(QtCore.QRect(160, 70, 321, 51))
        self.lineEditCateID.setStyleSheet("QLineEdit {\n"
"    font-size: 16px; /* Cỡ chữ */\n"
"    border: 2px solid #00806c; /* Viền xanh lá đậm */\n"
"    border-radius: 10px; /* Bo tròn góc */\n"
"    padding: 5px; /* Khoảng cách nội dung với viền */\n"
"    background-color: white; /* Nền trắng */\n"
"    color: #00806c; /* Chữ xanh đậm */\n"
"}\n"
"")
        self.lineEditCateID.setObjectName("lineEditCateID")
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSave.setGeometry(QtCore.QRect(10, 270, 111, 41))
        self.pushButtonSave.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../ima/save (2).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSave.setIcon(icon1)
        self.pushButtonSave.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonDelete.setGeometry(QtCore.QRect(260, 270, 111, 41))
        self.pushButtonDelete.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../ima/de.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonDelete.setIcon(icon2)
        self.pushButtonDelete.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.pushButtonShowall = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonShowall.setGeometry(QtCore.QRect(130, 270, 121, 41))
        self.pushButtonShowall.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../ima/showall.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonShowall.setIcon(icon3)
        self.pushButtonShowall.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonShowall.setObjectName("pushButtonShowall")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 121, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 140, 231, 31))
        self.label_8.setObjectName("label_8")
        self.lineEditCateName_2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditCateName_2.setGeometry(QtCore.QRect(20, 180, 471, 51))
        self.lineEditCateName_2.setStyleSheet("QLineEdit {\n"
"    font-size: 16px; /* Cỡ chữ */\n"
"    border: 2px solid #00806c; /* Viền xanh lá đậm */\n"
"    border-radius: 10px; /* Bo tròn góc */\n"
"    padding: 5px; /* Khoảng cách nội dung với viền */\n"
"    background-color: white; /* Nền trắng */\n"
"    color: #00806c; /* Chữ xanh đậm */\n"
"}\n"
"")
        self.lineEditCateName_2.setText("")
        self.lineEditCateName_2.setObjectName("lineEditCateName_2")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonExit.setGeometry(QtCore.QRect(380, 270, 111, 41))
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
"        border-radius: 15px;\n"
"        border-right: 1px solid #aaaaaa;\n"
"        border-bottom: 1px solid #aaaaaa;\n"
"        font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"        background-color: #00806c;\n"
"        color: White;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #dfc456;\n"
"        color: #fffffe;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed {\n"
"        background-color: #86ad6f;\n"
"        color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"        background-color: #aaaaaa;\n"
"        color: #ffffff;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../ima/exit (2).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon4)
        self.pushButtonExit.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(60, 340, 381, 261))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../ima/famer.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 1071, 48))
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setStyleSheet("font: 22pt \"Tahoma\";\n"
"color: rgb(26, 140, 118);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.labelBackground = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelBackground.setGeometry(QtCore.QRect(0, 0, 1111, 751))
        self.labelBackground.setText("")
        self.labelBackground.setPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../ima/nenanh.png"))
        self.labelBackground.setScaledContents(True)
        self.labelBackground.setObjectName("labelBackground")
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(30, 10, 111, 31))
        self.pushButtonBack.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border-right: 1px solid #aaaaaa;\n"
"    border-bottom: 1px solid #aaaaaa;\n"
"    font: bold 12pt \"Tahoma\"; /* Chữ in đậm */\n"
"    background-color: white;  /* Nền trắng */\n"
"    color: #0c2f70; /* Chữ xanh đậm */\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"    background-color: white;  /* Nền trắng */\n"
"    color: #0c2f70; /* Chữ xanh đậm */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #dfc456;\n"
"    color: #fffffe;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: #86ad6f;\n"
"    color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: white;\n"
"    color: #0c2f70; /* Xanh đậm */\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../ima/all.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBack.setIcon(icon5)
        self.pushButtonBack.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.labelBackground.raise_()
        self.layoutWidget.raise_()
        self.label.raise_()
        self.pushButtonBack.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 31))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../../../../../../Khanh Tran/.designer/images/9104334_sign out_logout_exit_out_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setObjectName("actionExit")
        self.importTXT_file = QtGui.QAction(parent=MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../../../../../../Khanh Tran/.designer/images/bxs-file-txt-512.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.importTXT_file.setIcon(icon7)
        self.importTXT_file.setObjectName("importTXT_file")
        self.importCSV_file = QtGui.QAction(parent=MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../../../../../../Khanh Tran/.designer/images/4344184.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.importCSV_file.setIcon(icon8)
        self.importCSV_file.setObjectName("importCSV_file")
        self.importXML_file = QtGui.QAction(parent=MainWindow)
        self.importXML_file.setObjectName("importXML_file")
        self.importJSON_file = QtGui.QAction(parent=MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../../../../../../Khanh Tran/.designer/images/3456434.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.importJSON_file.setIcon(icon9)
        self.importJSON_file.setObjectName("importJSON_file")
        self.importExcel_file = QtGui.QAction(parent=MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../../../../../../Khanh Tran/.designer/images/logo_brand_brands_logos_excel-512.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.importExcel_file.setIcon(icon10)
        self.importExcel_file.setObjectName("importExcel_file")
        self.importPickle_file = QtGui.QAction(parent=MainWindow)
        self.importPickle_file.setObjectName("importPickle_file")
        self.exportTXT_file = QtGui.QAction(parent=MainWindow)
        self.exportTXT_file.setIcon(icon7)
        self.exportTXT_file.setObjectName("exportTXT_file")
        self.exportCSV_file = QtGui.QAction(parent=MainWindow)
        self.exportCSV_file.setIcon(icon8)
        self.exportCSV_file.setObjectName("exportCSV_file")
        self.exportXML_file = QtGui.QAction(parent=MainWindow)
        self.exportXML_file.setObjectName("exportXML_file")
        self.exportJSON_file = QtGui.QAction(parent=MainWindow)
        self.exportJSON_file.setIcon(icon9)
        self.exportJSON_file.setObjectName("exportJSON_file")
        self.exportPickle_file = QtGui.QAction(parent=MainWindow)
        self.exportPickle_file.setObjectName("exportPickle_file")
        self.exportExcel_file = QtGui.QAction(parent=MainWindow)
        self.exportExcel_file.setIcon(icon10)
        self.exportExcel_file.setObjectName("exportExcel_file")
        self.actionHelp = QtGui.QAction(parent=MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../../../../../../Khanh Tran/.designer/images/9044348_help_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionHelp.setIcon(icon11)
        self.actionHelp.setObjectName("actionHelp")
        self.actionFeedback = QtGui.QAction(parent=MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("C:\\Users\\phuongthao\\PycharmProjects\\chuong5\\DOAN1\\ui\\../../../../../../Khanh Tran/.designer/images/8207898_about_info_information_help_ui_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionFeedback.setIcon(icon12)
        self.actionFeedback.setObjectName("actionFeedback")
        self.importJson_file = QtGui.QAction(parent=MainWindow)
        self.importJson_file.setObjectName("importJson_file")
        self.exportJson_file = QtGui.QAction(parent=MainWindow)
        self.exportJson_file.setObjectName("exportJson_file")
        self.actionCurrentHelp = QtGui.QAction(parent=MainWindow)
        self.actionCurrentHelp.setObjectName("actionCurrentHelp")
        self.menuHelp.addAction(self.actionCurrentHelp)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Products"))
        __sortingEnabled = self.listWidgetCategory.isSortingEnabled()
        self.listWidgetCategory.setSortingEnabled(False)
        item = self.listWidgetCategory.item(0)
        item.setText(_translate("MainWindow", "Trái cây"))
        item = self.listWidgetCategory.item(1)
        item.setText(_translate("MainWindow", "Rau củ"))
        item = self.listWidgetCategory.item(2)
        item.setText(_translate("MainWindow", "Thực phẩm hữu cơ"))
        item = self.listWidgetCategory.item(3)
        item.setText(_translate("MainWindow", "Nông sản địa phương"))
        item = self.listWidgetCategory.item(4)
        item.setText(_translate("MainWindow", "Sữa & Sản phẩm từ sữa"))
        item = self.listWidgetCategory.item(5)
        item.setText(_translate("MainWindow", "Thảo mộc & Gia vị"))
        item = self.listWidgetCategory.item(6)
        item.setText(_translate("MainWindow", "Trứng gà, vịt"))
        item = self.listWidgetCategory.item(7)
        item.setText(_translate("MainWindow", "Khác"))
        self.listWidgetCategory.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("MainWindow", "Category Details:"))
        self.pushButtonSave.setText(_translate("MainWindow", " Save"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Delete"))
        self.pushButtonShowall.setText(_translate("MainWindow", "Show all"))
        self.label_7.setText(_translate("MainWindow", "Cate ID:"))
        self.label_8.setText(_translate("MainWindow", "Cate Description:"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit "))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#30806c;\">Product Management</span></p></body></html>"))
        self.pushButtonBack.setText(_translate("MainWindow", "Back"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Esc"))
        self.importTXT_file.setText(_translate("MainWindow", "txt file"))
        self.importTXT_file.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.importCSV_file.setText(_translate("MainWindow", "csv file"))
        self.importCSV_file.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.importXML_file.setText(_translate("MainWindow", "xml file"))
        self.importJSON_file.setText(_translate("MainWindow", "json file"))
        self.importExcel_file.setText(_translate("MainWindow", "excel file"))
        self.importExcel_file.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.importPickle_file.setText(_translate("MainWindow", "pickle file"))
        self.exportTXT_file.setText(_translate("MainWindow", "txt file"))
        self.exportTXT_file.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.exportCSV_file.setText(_translate("MainWindow", "csv file"))
        self.exportCSV_file.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.exportXML_file.setText(_translate("MainWindow", "xml file"))
        self.exportJSON_file.setText(_translate("MainWindow", "json file"))
        self.exportPickle_file.setText(_translate("MainWindow", "pickle file"))
        self.exportExcel_file.setText(_translate("MainWindow", "excel file"))
        self.exportExcel_file.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1"))
        self.actionFeedback.setText(_translate("MainWindow", "Feedback"))
        self.actionFeedback.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.importJson_file.setText(_translate("MainWindow", "json file"))
        self.exportJson_file.setText(_translate("MainWindow", "json file"))
        self.actionCurrentHelp.setText(_translate("MainWindow", "Current Help"))
